const error = {
    // USER
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
    USERNAME_ALREADY_EXIST: 'USERNAME_ALREADY_EXIST',
    USER_LIST_NOT_EXIST: 'CANNOT OBTAIN LIST USER',

    // TOKEN
    UNAUTHORIZE: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN'
}

module.exports = error