const error = {
    // USER
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
    USERNAME_ALREADY_EXIST: 'USERNAME_ALREADY_EXIST',
    USER_LIST_NOT_EXIST: 'CANNOT OBTAIN LIST USER',

    // TOKEN
    UNAUTHORIZE: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_ALLOW: 'NOT_ALLOW',

    //POST 
    CATEGORY_LIST_NOT_EXIST: 'CATEGORY_NOT_EXIST',
    POST_NOT_FOUND: 'POST_NOT_FOUND',

    //FORUM-THREAD
    THREAD_LIST_NOT_EXIST: 'CANNOT OBTAIN LIST THREAD',

    //FORUM-TOPIC
    TOPIC_LIST_NOT_EXIST: 'CANNOT OBTAIN LIST TOPIC',

    BAD_REQUEST: 'BAD_REQUEST',

    //FILE 
    NO_FILE_UPLOAD: 'NO_FILE_UPLOAD',

    //COMMENT
    COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND'
}

module.exports = error