const succeed = {
    LOGIN_SUCCEED: 'LOGIN_SUCCEED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',

    GET_USERLIST_SUCCESS: 'OBTAIN LIST USER SUCCESSFULLY',

    //POST
    GET_CATEGORYLIST_SUCCESS: 'OBTAIN LIST CATEGORY SUCCESSFULLY',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS'
}

module.exports = succeed