const succeed = {
    LOGIN_SUCCEED: 'LOGIN_SUCCEED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',

    //USER
    GET_USERLIST_SUCCESS: 'OBTAIN LIST USER SUCCESSFULLY',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    BLOCK_USER_SUCCESS: 'BLOCK_USER_SUCCESS',
    UNBLOCK_USER_SUCCESS: 'UNBLOCK_USER_SUCCESS',

    //POST
    GET_CATEGORYLIST_SUCCESS: 'OBTAIN LIST CATEGORY SUCCESSFULLY',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    CREATE_POST_SUCCESS: ' CREATE_POST_SUCCESS',

    //COMMENT
    GET_COMMENT_SUCCESS: 'GET_COMMENT_SUCCESS',
    CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
    DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
    UPDATE_COMMENT_SUCCESS: 'UPDATE_COMMENT_SUCCESS',

    //FORUM-THREAD
    GET_THREADLIST_SUCCESS: 'OBTAIN LIST THREAD SUCCESSFULLY',

    //FORUM-TOPIC
    GET_TOPICLIST_SUCCESS: 'OBTAIN LIST TOPIC SUCCESSFULLY',
    CREATE_TOPIC_SUCCESS: 'CREATE_TOPIC_SUCCESS',
    UPDATE_TOPIC_SUCCESS: 'UPDATE_TOPIC_SUCCESS',
    DELETE_TOPIC_SUCCESS: 'DELETE_TOPIC_SUCCESS',

    //FORUM-REACT
    CREATE_REACT_SUCCESS: 'CREATE_REACT_SUCCESS',
    DELETE_REACT_SUCCESS: 'DELETE_REACT_SUCCESS',
    GET_REACT_SUCCESS: 'GET_REACT_SUCCESS'
}

module.exports = succeed